"""
Run this in the same folder as both cards.json and card_names_i18n.js.

cards.json is keyed by some internal "cid", but each entry also has an "id"
field -- the real passcode, same numbers used as keys in card_names_i18n.js.
For every passcode we have in card_names_i18n.js, if cards.json has a
matching "id" with a non-empty "nwbbs_n" (the more commonly-spoken name),
that replaces the existing "sc_name" value. Cards with no match, or with an
empty nwbbs_n, keep whatever sc_name they already had.

No network access needed -- everything here is local file processing.
"""

import json
import re

CN_DB_FILE = "cards.json"
I18N_FILE = "card_names_i18n.js"

print(f"Loading {CN_DB_FILE}...")
with open(CN_DB_FILE, encoding="utf-8") as f:
    cn_db = json.load(f)
print(f"Got {len(cn_db)} entries.")

# Build passcode -> common name mapping. A passcode could theoretically show
# up more than once in cards.json (e.g. different internal cid entries for
# reprints) -- first non-empty match wins, rest are skipped.
passcode_to_nwbbs = {}
skipped_duplicates = 0
for entry in cn_db.values():
    passcode = str(entry.get("id", "")).strip()
    nwbbs = (entry.get("nwbbs_n") or "").strip()
    if not passcode or not nwbbs:
        continue
    if passcode in passcode_to_nwbbs:
        skipped_duplicates += 1
        continue
    passcode_to_nwbbs[passcode] = nwbbs

print(f"Built {len(passcode_to_nwbbs)} passcode -> common name mappings "
      f"({skipped_duplicates} duplicate passcodes skipped).")

print(f"\nLoading {I18N_FILE}...")
with open(I18N_FILE, encoding="utf-8") as f:
    content = f.read()

match = re.search(r"=\s*(\{.*\})\s*;?\s*$", content, re.DOTALL)
data = json.loads(match.group(1))
print(f"Got {len(data)} cards.")

updated = 0
examples = []
for card_id, names in data.items():
    if card_id in passcode_to_nwbbs:
        new_name = passcode_to_nwbbs[card_id]
        if names.get("sc_name") != new_name:
            if len(examples) < 10:
                examples.append((card_id, names.get("sc_name"), new_name))
            names["sc_name"] = new_name
            updated += 1

print(f"\nUpdated sc_name for {updated} of {len(data)} cards.")
if examples:
    print("\nExamples of changes:")
    for card_id, old, new in examples:
        print(f"  {card_id}: {old!r} -> {new!r}")

with open(I18N_FILE, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by fetch_translations.py -- do not edit by hand.\n")
    f.write("window.CARD_NAMES_I18N = ")
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write(";\n")

print(f"\nWrote {I18N_FILE}.")
